### ISSUE TITLE
Alte/nicht genutzte Branches löschen

### ISSUE THREAD

**Issue by enricopau** [haevg-rz/go-updater#50]
Es liegen noch viele Branches offen, die gelöscht werden können. 
Main scheint alle Änderungen zu beinhalten: 
![image](https://user-images.githubusercontent.com/32924566/112104865-fc178380-8bab-11eb-8f64-35d843127aa7.png)

![image](https://user-images.githubusercontent.com/32924566/112104975-20736000-8bac-11eb-9bab-970d503982c8.png)

**Comment by KaHBrat** [comment]
Done ;)
